### ISSUE TITLE
Missing functionality as shown in the demo?

### ISSUE THREAD

**Issue by abhilash29** [SimHub/responsive_nodejs_chat#2]
The project does not contain room creation functionality as shown in the demo.
![capture](https://cloud.githubusercontent.com/assets/1309199/24319648/f8f7cf62-1147-11e7-8fe2-132420bd9e29.PNG)

**Comment by SimHub** [comment]
hi abhilash29 ,
i added a Room_Example Folder.
try it out :smirk:
